<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ask a Specialist_mega-indicator</name>
   <tag></tag>
   <elementGuidId>c490706c-0b57-4178-b9fe-fa3e8f307574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mega-indicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mega-menu-item-198']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d3f0c0a-3948-4ba9-9024-6e65fdb9b9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-indicator</value>
      <webElementGuid>b6eb856d-61bd-4690-b9d2-af18c0eedc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-click-event</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c84dc2e-d7e4-4373-9b47-e5fe956ddd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mega-menu-item-198&quot;)/a[@class=&quot;mega-menu-link&quot;]/span[@class=&quot;mega-indicator&quot;]</value>
      <webElementGuid>148b4960-b68d-4afa-91ae-a3f4e141ecbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mega-menu-item-198']/a/span</value>
      <webElementGuid>8bb4d15d-387d-4c9f-997f-ec4e41c1910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>b7aba978-4edb-4a8c-a713-14ab76593d39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
