<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_hellomagicminds.io_normallogo</name>
   <tag></tag>
   <elementGuidId>782017c3-137d-416b-87f6-0668b7e13916</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.normallogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home']/header/nav/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>90296c83-a799-4122-85fa-6c197d015b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magicminds.io/wp-content/uploads/2023/03/cropped-logo-1.png</value>
      <webElementGuid>1b6d6c72-8935-47a4-9c99-ea3b5a208de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normallogo</value>
      <webElementGuid>529d1a70-63a9-4b76-9da7-9fa477f0382e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>95ffb357-4b3f-4194-9d7c-5352155ecca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/header[@class=&quot;header&quot;]/nav[@class=&quot;navbar navbar-expand-xl navbar-light headnav&quot;]/div[@class=&quot;container&quot;]/a[@class=&quot;navbar-brand logo&quot;]/img[@class=&quot;normallogo&quot;]</value>
      <webElementGuid>26bbd1c1-e031-4f7e-bc6f-c1953ffa725f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/header/nav/div/a/img</value>
      <webElementGuid>50e8f58e-0cdd-49bd-948c-be290d4fd8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>de973e69-0f18-41d9-9090-bbd402f9c322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fa8bea91-08ae-4d4b-8292-f4a2a7fa8d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magicminds.io/wp-content/uploads/2023/03/cropped-logo-1.png' and @alt = 'logo']</value>
      <webElementGuid>5f39adb0-b19a-4f6a-a231-76f7525f2132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
